### ISSUE TITLE
Ubuntu 12.04/14.04 - nagios3 packages ship with conf.d/ configs that contain duplicate contacts, etc

### ISSUE THREAD

**Issue by wayne530** [schubergphilis/nagios#287] opened 2014-06-29 03:28 UTC
Ubuntu 12.04 - nagios3-3.2.3-3ubuntu1
Ubuntu 14.04 - nagios3-3.5.1-1ubuntu1

It appears the packages contain default configs located in /etc/nagios3/conf.d with the suffix _nagios2.cfg. These config files contain definitions for the root contact and others, which causes Nagios to fail to start. Removing *_nagios2.cfg seems to fix the issue.

**Comment by sbotman** [comment] 2015-08-19 09:57
The latest cookbook version will zap out all configuration files that are not maintained by chef. This should solve your problem that you are describing here above. Closing the ticket, but please feel free to re-open this if the problem is still active.

**Closed by sbotman** 2015-08-19 09:57 UTC
